#pragma once
#ifndef enum_h_
#define enum_h_

#include "initGame.h"

enum NumberOfCharacter
{
	CHARACTER_1,
	CHARACTER_2,
	CHARACTER_3,
	CHARACTER_4,
	ALLCHARACTER
};

enum NumberOfMonster
{
	MONSTER_1,
	MONSTER_2,
	MONSTER_3,
	MONSTER_4,
	MONSTER_5,
	MONSTER_6,
	MONSTER_7,
	MONSTER_8,
	ALLMONSTER
};

enum NumberOfSkillChracter
{
	CHARACTER_NORMAL,
	CHARACTER_ELEMENTAL,
	CHARACTER_ULTI,
	CHARACTER_ALLSKILL
};

enum NumberOfSkillBoss
{
	BOSS_SKILL_1,
	BOSS_SKILL_2,
	BOSS_SKILL_3,
	BOSS_SKILL_4,
	BOSS_ALLSKILL
};

enum StatOfCharacter
{
	CHARACTER_HP,
	CHARACTER_ATK,
	CHARACTER_DEF,
	CHARACTER_SPEED,
	CHARACTER_ALLSTAT
};

enum StatOfMonster
{
	MONSTER_CURRENT_HP,
	MONSTER_MAXHP,
	MONSTER_ATK,
	MONSTER_DEF,
	MONSTER_SPEED,
	MONSTER_ALLSTAT
};

enum CharacterAction
{
	CHARACTER_RUN,
	CHARACTER_DIE,
	CHARACTER_ATTACK,
	CHARACTER_ALLACTION
};

enum BossAction
{
	BOSS_STAND,
	BOSS_RUN,
	BOSS_DIE,
	BOSS_ATTACK,
	BOSS_ALLACTION
};

enum MonsterAction
{
	MONSTER_RUN,
	MONSTER_DIE,
	MONSTER_ATTACK,
	MONSTER_ALLACTION
};

enum SkillCharacter
{
	N1,
	E1,
	Q1,
	N2,
	E2,
	Q2,
	N3,
	E3,
	Q3,
	N4,
	E4,
	Q4,
};

enum SizeOfBulletCharacter
{
	N1_WIDTH = 20,
	N1_HEIGHT = 10,
	E1_WIDTH = 50,
	E1_HEIGHT = 50,
	Q1_WIDTH = 100,
	Q1_HEIGHT = 100,

	N2_WIDTH = 60,
	N2_HEIGHT = 10,
	E2_WIDTH = 50,
	E2_HEIGHT = 50,
	Q2_WIDTH = 150,
	Q2_HEIGHT = 250,

	N3_WIDTH = 50,
	N3_HEIGHT = 50,
	E3_WIDTH = 50,
	E3_HEIGHT = 50,
	Q3_WIDTH = 80,
	Q3_HEIGHT = 10,

	N4_WIDTH = 30,
	N4_HEIGHT = 20,
	E4_WIDTH = 40,
	E4_HEIGHT = 20,
	Q4_WIDTH = 70,
	Q4_HEIGHT = 50
};

enum SizeOfBulletMonster
{
	MONSTER_5_BULLET_WIDTH = 15,
	MONSTER_5_BULLET_HEIGHT = 7,
	MONSTER_8_BULLET_WIDTH = 20,
	MONSTER_8_BULLET_HEIGHT = 10,
};

enum SizeOfCharacter
{
	CHARACTER_WIDTH = 50,
	CHARACTER_HEIGHT = 50
};

enum SizeOfMonster
{
	MONSTER_1_WIDTH = 60,
	MONSTER_1_HEIGHT = 60,
	MONSTER_2_WIDTH = 30,
	MONSTER_2_HEIGHT = 30,
	MONSTER_3_WIDTH = 60,
	MONSTER_3_HEIGHT = 60,
	MONSTER_4_WIDTH = 40,
	MONSTER_4_HEIGHT = 30,
	MONSTER_5_WIDTH = 60,
	MONSTER_5_HEIGHT = 60,
	MONSTER_6_WIDTH = 60,
	MONSTER_6_HEIGHT = 60,
	MONSTER_7_WIDTH = 60,
	MONSTER_7_HEIGHT = 60,
	MONSTER_8_WIDTH = 100,
	MONSTER_8_HEIGHT = 100
};

enum ItemName
{
	ITEM_HEAL,
	ITEM_ATK,
	ITEM_DEF,
	ALLITEM
};

enum ItemSize
{
	ITEM_WIDTH = 50,
	ITEM_HEIGHT = 50
};

enum MapNumber
{
	MAP_1,
	MAP_2,
	ALLMAP
};

enum MenuFeatures
{
	MENU_PAUSE_BUTTON,
	MENU_RESUME_BUTTON,
	MENU_HELP_BUTTON,
	MENU_REPLAY_BUTTON,
	MENU_SETTING_BUTTON,
	MENU_MENU_WORD,
	MENU_QUIT_WINDOW_BUTTON,
	MENU_WINDOW,
	MENU_WELCOMSCREEN,
	MENU_START_BUTTON,
	MENU_CLICKTOPLAY_WORD,
	MENU_MAP_WORD,
	MENU_MAP_IMAGE,
	MENU_ARROW_LEFT,
	MENU_ARROW_RIGHT,
	MENU_NUMBER_MAP_WORD,
	MENU_ALL
};

enum MenuSize
{
	MENU_PAUSE_BUTTON_WIDTH = 100,
	MENU_PAUSE_BUTTON_HEIGHT = 100,
	MENU_RESUME_BUTTON_WIDTH = 100,
	MENU_RESUME_BUTTON_HEIGHT = 100,
	MENU_HELP_BUTTON_WIDTH = 100,
	MENU_HELP_BUTTON_HEIGHT = 100,
	MENU_REPLAY_BUTTON_WIDTH = 100,
	MENU_REPLAY_BUTTON_HEIGHT = 100,
	MENU_SETTING_BUTTON_WIDTH = 40,
	MENU_SETTING_BUTTON_HEIGHT = 40,
	MENU_MENU_WORD_WIDTH = 200,
	MENU_MENU_WORD_HEIGHT = 100,
	MENU_QUIT_WINDOW_BUTTON_WIDTH = 30,
	MENU_QUIT_WINDOW_BUTTON_HEIGHT = 30,
	MENU_WINDOW_WIDTH = 400,
	MENU_WINDOW_HEIGHT = 400,
	MENU_WELCOMSCREEN_WIDTH = 1400,
	MENU_WELCOMSCREEN_HEIGHT = 800,
	MENU_START_BUTTON_WIDTH = 200,
	MENU_START_BUTTON_HEIGHT = 100,
	MENU_CLICKTOPLAY_WORD_WIDTH = 400,
	MENU_CLICKTOPLAY_WORD_HEIGHT = 30,
	MENU_MAP_WORD_WIDTH = 140,
	MENU_MAP_WORD_HEIGHT = 70,
	MENU_MAP_IMAGE_WIDTH = 400,
	MENU_MAP_IMAGE_HEIGHT = 300,
	MENU_ARROW_LEFT_WIDTH = 100,
	MENU_ARROW_LEFT_HEIGHT = 300,
	MENU_ARROW_RIGHT_WIDTH = 100,
	MENU_ARROW_RIGHT_HEIGHT = 300,
	MENU_NUMBER_MAP_WORD_WIDTH = 100,
	MENU_NUMBER_MAP_WORD_HEIGHT = 30,
};

enum MenuPosition
{
	MENU_PAUSE_BUTTON_X = 500,
	MENU_PAUSE_BUTTON_Y = 450,
	MENU_RESUME_BUTTON_X = 600,
	MENU_RESUME_BUTTON_Y = 450,
	MENU_HELP_BUTTON_X = 700,
	MENU_HELP_BUTTON_Y = 450,
	MENU_REPLAY_BUTTON_X = 800,
	MENU_REPLAY_BUTTON_Y = 450,
	MENU_SETTING_BUTTON_X = 1360,
	MENU_SETTING_BUTTON_Y = 40,
	MENU_MENU_WORD_X = 600,
	MENU_MENU_WORD_Y = 250,
	MENU_QUIT_WINDOW_BUTTON_X = 880,
	MENU_QUIT_WINDOW_BUTTON_Y = 220,
	MENU_WINDOW_X = 500,
	MENU_WINDOW_Y = 200,
	MENU_WELCOMSCREEN_X = 0,
	MENU_WELCOMSCREEN_Y = 0,
	MENU_START_BUTTON_X = 1200,
	MENU_START_BUTTON_Y = 700,
	MENU_CLICKTOPLAY_WORD_X = 500,
	MENU_CLICKTOPLAY_WORD_Y = 650,
	MENU_MAP_WORD_X = 630,
	MENU_MAP_WORD_Y = 265,
	MENU_MAP_IMAGE_X = 500,
	MENU_MAP_IMAGE_Y = 300,
	MENU_ARROW_LEFT_X = 370,
	MENU_ARROW_LEFT_Y = 250,
	MENU_ARROW_RIGHT_X = 930,
	MENU_ARROW_RIGHT_Y = 250,
	MENU_NUMBER_MAP_WORD_X = 650,
	MENU_NUMBER_MAP_WORD_Y = 685,
};

#endif enum_h_