#pragma once
#ifndef enum_h_
#define enum_h_

#include "initGame.h"

enum NumberOfCharacter
{
	CHARACTER_1,
	CHARACTER_2,
	CHARACTER_3,
	CHARACTER_4,
	ALLCHARACTER
};

enum NumberOfMonster
{
	MONSTER_1,
	MONSTER_2,
	MONSTER_3,
	MONSTER_4,
	MONSTER_5,
	MONSTER_6,
	MONSTER_7,
	MONSTER_8,
	MONSTER_9,
	ALLMONSTER
};

enum NumberOfSkillChracter
{
	CHARACTER_NORMAL,
	CHARACTER_ELEMENTAL,
	CHARACTER_ULTI,
	CHARACTER_ALLSKILL
};

enum NumberOfSkillBoss
{
	BOSS_SKILL1,
	BOSS_SKILL2,
	BOSS_SKILL3,
	BOSS_SKILL4,
	BOSS_ALLSKILL
};

enum StatOfCharacter
{
	CHARACTER_HP,
	CHARACTER_ATK,
	CHARACTER_DEF,
	CHARACTER_SPEED,
	CHARACTER_ALLSTAT
};

enum StatOfMonster
{
	MONSTER_CURRENT_HP,
	MONSTER_MAXHP,
	MONSTER_ATK,
	MONSTER_DEF,
	MONSTER_SPEED,
	MONSTER_ALLSTAT
};

enum CharacterAction
{
	CHARACTER_RUN,
	CHARACTER_DIE,
	CHARACTER_ATTACK,
	CHARACTER_ALLACTION
};

enum BossAction
{
	BOSS_STAND,
	BOSS_DIE,
	BOSS_ATTACK,
	BOSS_ALLACTION
};

enum MonsterAction
{
	MONSTER_RUN,
	MONSTER_DIE,
	MONSTER_ATTACK,
	MONSTER_ALLACTION
};

enum SkillCharacter
{
	N1,
	E1,
	Q1,
	N2,
	E2,
	Q2,
	N3,
	E3,
	Q3,
	N4,
	E4,
	Q4,
};

enum SizeOfBulletCharacter
{
	N1_WIDTH = 20,
	N1_HEIGHT = 10,
	E1_WIDTH = 50,
	E1_HEIGHT = 50,
	Q1_WIDTH = 100,
	Q1_HEIGHT = 100,

	N2_WIDTH = 60,
	N2_HEIGHT = 10,
	E2_WIDTH = 50,
	E2_HEIGHT = 50,
	Q2_WIDTH = 150,
	Q2_HEIGHT = 250,

	N3_WIDTH = 50,
	N3_HEIGHT = 50,
	E3_WIDTH = 50,
	E3_HEIGHT = 50,
	Q3_WIDTH = 80,
	Q3_HEIGHT = 10,

	N4_WIDTH = 30,
	N4_HEIGHT = 20,
	E4_WIDTH = 40,
	E4_HEIGHT = 20,
	Q4_WIDTH = 70,
	Q4_HEIGHT = 50
};

enum SizeOfBulletMonster
{
	MONSTER_5_BULLET_WIDTH = 15,
	MONSTER_5_BULLET_HEIGHT = 7,
	MONSTER_8_BULLET_WIDTH = 20,
	MONSTER_8_BULLET_HEIGHT = 10,
};

enum SizeOfCharacter
{
	CHARACTER_WIDTH = 50,
	CHARACTER_HEIGHT = 50
};

enum SizeOfMonster
{
	MONSTER_1_WIDTH = 60,
	MONSTER_1_HEIGHT = 60,
	MONSTER_2_WIDTH = 30,
	MONSTER_2_HEIGHT = 30,
	MONSTER_3_WIDTH = 60,
	MONSTER_3_HEIGHT = 60,
	MONSTER_4_WIDTH = 40,
	MONSTER_4_HEIGHT = 30,
	MONSTER_5_WIDTH = 60,
	MONSTER_5_HEIGHT = 60,
	MONSTER_6_WIDTH = 60,
	MONSTER_6_HEIGHT = 60,
	MONSTER_7_WIDTH = 60,
	MONSTER_7_HEIGHT = 60,
	MONSTER_8_WIDTH = 100,
	MONSTER_8_HEIGHT = 100,
	MONSTER_9_WIDTH = 50,
	MONSTER_9_HEIGHT = 50

};

enum ItemName
{
	ITEM_HEAL,
	ITEM_ATK,
	ITEM_DEF,
	ALLITEM
};

enum ItemSize
{
	ITEM_WIDTH = 50,
	ITEM_HEIGHT = 50
};

enum MapNumber
{
	MAP_1,
	MAP_2,
	MAP_BOSS,
	ALLMAP
};

enum MenuFeatures
{
	MENU_SETTING_BUTTON,
	MENU_RESUME_BUTTON,
	MENU_HELP_BUTTON,
	MENU_REPLAY_BUTTON,
	MENU_MUSIC_BUTTON,
	MENU_HOME_BUTTON,
	MENU_PAY_BUTTON,
	MENU_MENU_WORD,	
	MENU_QUIT_WINDOW_BUTTON,
	MENU_WINDOW,
	MENU_WELCOMSCREEN,
	MENU_SURVIVOR,
	MENU_START_BUTTON,
	MENU_CLICKTOPLAY_WORD,
	MENU_MAP_WORD,
	MENU_MAP_IMAGE,
	MENU_NUMBER_MAP_WORD,
	MENU_ARROW_LEFT,
	MENU_ARROW_RIGHT,
	MENU_PLAY_BUTTON,
	MENU_NEXT_BUTTON,
	MENU_BACK_BUTTON,
	ALLMENU
};

enum MenuSize
{
	MENU_SETTING_BUTTON_WIDTH = 40,
	MENU_SETTING_BUTTON_HEIGHT = 40,
	MENU_RESUME_BUTTON_WIDTH = 100,
	MENU_RESUME_BUTTON_HEIGHT = 100,
	MENU_HELP_BUTTON_WIDTH = 100,
	MENU_HELP_BUTTON_HEIGHT = 100,
	MENU_REPLAY_BUTTON_WIDTH = 100,
	MENU_REPLAY_BUTTON_HEIGHT = 100,
	MENU_MUSIC_BUTTON_WIDTH = 100,
	MENU_MUSIC_BUTTON_HEIGHT = 100,
	MENU_HOME_BUTTON_WIDTH = 100,
	MENU_HOME_BUTTON_HEIGHT = 100,
	MENU_PAY_BUTTON_WIDTH = 100,
	MENU_PAY_BUTTON_HEIGHT = 100,
	MENU_MENU_WORD_WIDTH = 400,
	MENU_MENU_WORD_HEIGHT = 100,
	MENU_QUIT_WINDOW_BUTTON_WIDTH = 50,
	MENU_QUIT_WINDOW_BUTTON_HEIGHT = 50,
	MENU_WINDOW_WIDTH = 900,
	MENU_WINDOW_HEIGHT = 500,
	MENU_WELCOMSCREEN_WIDTH = 1400,
	MENU_WELCOMSCREEN_HEIGHT = 800,
	MENU_SURVIVOR_WIDTH = 800,
	MENU_SURVIVOR_HEIGHT = 250,
	MENU_START_BUTTON_WIDTH = 200,
	MENU_START_BUTTON_HEIGHT = 100,
	MENU_CLICKTOPLAY_WORD_WIDTH = 600,
	MENU_CLICKTOPLAY_WORD_HEIGHT = 40,
	MENU_MAP_WORD_WIDTH = 140,
	MENU_MAP_WORD_HEIGHT = 70,
	MENU_MAP_IMAGE_WIDTH = 400,
	MENU_MAP_IMAGE_HEIGHT = 300,
	MENU_NUMBER_MAP_WORD_WIDTH = 100,
	MENU_NUMBER_MAP_WORD_HEIGHT = 30,
	MENU_ARROW_LEFT_WIDTH = 100,
	MENU_ARROW_LEFT_HEIGHT = 300,
	MENU_ARROW_RIGHT_WIDTH = 100,
	MENU_ARROW_RIGHT_HEIGHT = 300,
	MENU_PLAY_BUTTON_WIDTH = 100,
	MENU_PLAY_BUTTON_HEIGHT = 40,
	MENU_NEXT_BUTTON_WIDTH = 100,
	MENU_NEXT_BUTTON_HEIGHT = 50,
	MENU_BACK_BUTTON_WIDTH = 100,
	MENU_BACK_BUTTON_HEIGHT = 50
};

enum MenuPosition
{
	MENU_SETTING_BUTTON_X = 1355,
	MENU_SETTING_BUTTON_Y = 5,
	MENU_RESUME_BUTTON_X = 400,
	MENU_RESUME_BUTTON_Y = 300,
	MENU_HELP_BUTTON_X = 900,
	MENU_HELP_BUTTON_Y = 500,
	MENU_REPLAY_BUTTON_X = 650,
	MENU_REPLAY_BUTTON_Y = 300,
	MENU_MUSIC_BUTTON_X = 400,
	MENU_MUSIC_BUTTON_Y = 500,
	MENU_HOME_BUTTON_X = 900,
	MENU_HOME_BUTTON_Y = 300,
	MENU_PAY_BUTTON_X = 650,
	MENU_PAY_BUTTON_Y = 500,
	MENU_MENU_WORD_X = 500,
	MENU_MENU_WORD_Y = 60,
	MENU_QUIT_WINDOW_BUTTON_X = 1100,
	MENU_QUIT_WINDOW_BUTTON_Y = 150,
	MENU_WINDOW_X = 250,
	MENU_WINDOW_Y = 150,
	MENU_WELCOMSCREEN_X = 0,
	MENU_WELCOMSCREEN_Y = 0,
	MENU_SURVIVOR_X = 350,
	MENU_SURVIVOR_Y = 80,
	MENU_START_BUTTON_X = 600,
	MENU_START_BUTTON_Y = 550,
	MENU_CLICKTOPLAY_WORD_X = 400,
	MENU_CLICKTOPLAY_WORD_Y = 700,
	MENU_MAP_WORD_X = 630,
	MENU_MAP_WORD_Y = 180,
	MENU_MAP_IMAGE_X = 500,
	MENU_MAP_IMAGE_Y = 250,
	MENU_NUMBER_MAP_WORD_X = 650,
	MENU_NUMBER_MAP_WORD_Y = 685,
	MENU_ARROW_LEFT_X = 370,
	MENU_ARROW_LEFT_Y = 250,
	MENU_ARROW_RIGHT_X = 930,
	MENU_ARROW_RIGHT_Y = 250,
	MENU_PLAY_BUTTON_X = 1290,
	MENU_PLAY_BUTTON_Y = 750,
	MENU_NEXT_BUTTON_X = 1280,
	MENU_NEXT_BUTTON_Y = 720,
	MENU_BACK_BUTTON_X = 20,
	MENU_BACK_BUTTON_Y = 720
};

enum AppState
{
	STATE_START,
	STATE_LAYOUT,
	STATE_SETTING,
	STATE_PAUSE,
	STATE_RESUME,
	STATE_REPLAY,
	STATE_HOME,
	STATE_MUSIC,
	STATE_PAY,
	STATE_HELP,
	STATE_MAP1,
	STATE_MAP2,
	STATE_MAPBOSS,
	STATE_SUMMARY,
	STATE_END,
	STATE_RESET,
	ALLSTATE
};

enum Color
{
	COLOR_WHITE,
	COLOR_YEALLOW,
	COLOR_GRAY,
	COLOR_ORANGE,
	COLOR_BROWN,
	COLOR_BLACK,
	ALLCOLOR
};

enum TTF_VILLA
{
	FONT_CLIKTOPLAY,
	FONT_MENU,
	FONT_MAP,
	FONT_MAP1,
	FONT_MAP2,
	FONT_MAPBOSS,
	FONT_TIME_REMAINING,
	FONT_SCORE,
	ALLFONT
};

enum PaymentFeatures
{
	PAY_WINDOW,
	PAY_QUITWINDOW,
	PAY_QUITRESULT,
	PAY_TITLE,
	PAY_QR,
	PAY_CIRCLE1,
	PAY_CIRCLE2,
	PAY_CIRCLE3,
	PAY_CIRCLE4,
	PAY_GREENTICK,
	PAY_BIDV,
	PAY_TPBANK,
	PAY_MOMO,
	PAY_VIETTELPAY,
	PAY_OK,
	PAY_SALE,
	PAY_ENTER_NAME,
	PAY_BOX_NAME,
	PAY_NAME_WORD,
	PAY_ENTER_VALUE,
	PAY_BOX_VALUE,
	PAY_VALUE_WORD,
	PAY_BOX_RESULT,
	PAY_RESULT_WORD,
	PAY_CHOOSE_BANK,
	ALLPAY
};

enum PaymentSize
{
	PAY_WINDOW_WIDTH = 1200,
	PAY_WINDOW_HEIGHT = 700,
	PAY_QUITRESULT_WIDTH = 40,
	PAY_QUITRESULT_HEIGHT = 40,
	PAY_QUITWINDOW_WIDTH = 40,
	PAY_QUITWINDOW_HEIGHT = 40,
	PAY_TITLE_WIDTH = 400,
	PAY_TITLE_HEIGHT = 100,
	PAY_QR_WIDTH = 200,
	PAY_QR_HEIGHT = 200,
	PAY_CIRCLE1_WIDTH = 30,
	PAY_CIRCLE1_HEIGHT = 30,
	PAY_CIRCLE2_WIDTH = 30,
	PAY_CIRCLE2_HEIGHT = 30,
	PAY_CIRCLE3_WIDTH = 30,
	PAY_CIRCLE3_HEIGHT = 30,
	PAY_CIRCLE4_WIDTH = 30,
	PAY_CIRCLE4_HEIGHT = 30,
	PAY_GREENTICK_WIDTH = 30,
	PAY_GREENTICK_HEIGHT = 30,
	PAY_BIDV_WIDTH = 100,
	PAY_BIDV_HEIGHT = 100,
	PAY_MOMO_WIDTH = 100,
	PAY_MOMO_HEIGHT = 100,
	PAY_TPBANK_WIDTH = 100,
	PAY_TPBANK_HEIGHT = 100,
	PAY_VIETTELPAY_WIDTH = 100,
	PAY_VIETTELPAY_HEIGHT = 100,
	PAY_OK_WIDTH = 100,
	PAY_OK_HEIGHT = 60,
	PAY_SALE_WIDTH = 400,
	PAY_SALE_HEIGHT = 100,
	PAY_ENTER_NAME_WIDTH = 100,
	PAY_ENTER_NAME_HEIGHT = 15,
	PAY_BOX_NAME_WIDTH = 780,
	PAY_BOX_NAME_HEIGHT = 50,
	PAY_NAME_WORD_WIDTH = 0,
	PAY_NAME_WORD_HEIGHT = 40,
	PAY_ENTER_VALUE_WIDTH = 250,
	PAY_ENTER_VALUE_HEIGHT = 15,
	PAY_BOX_VALUE_WIDTH = 780,
	PAY_BOX_VALUE_HEIGHT = 50,
	PAY_VALUE_WORD_WIDTH = 0,
	PAY_VALUE_WORD_HEIGHT = 40,
	PAY_BOX_RESULT_WIDTH = 1000,
	PAY_BOX_RESULT_HEIGHT = 200,
	PAY_RESULT_WORD_WIDTH = 0,
	PAY_RESULT_WORD_HEIGHT = 50,
	PAY_CHOOSE_BANK_WIDTH = 200,
	PAY_CHOOSE_BANK_HEIGHT = 15
};

enum PaymentPosition
{
	PAY_WINDOW_X = 100,
	PAY_WINDOW_Y = 50,
	PAY_QUITRESULT_X = 1155,
	PAY_QUITRESULT_Y = 300,
	PAY_QUITWINDOW_X = 1240,
	PAY_QUITWINDOW_Y = 60,
	PAY_TITLE_X = 500,
	PAY_TITLE_Y = 60,
	PAY_QR_X = 210,
	PAY_QR_Y = 280,
	PAY_CIRCLE1_X = 485,
	PAY_CIRCLE1_Y = 620,
	PAY_CIRCLE2_X = 685,
	PAY_CIRCLE2_Y = 620,
	PAY_CIRCLE3_X = 885,
	PAY_CIRCLE3_Y = 620,
	PAY_CIRCLE4_X = 1085,
	PAY_CIRCLE4_Y = 620,
	PAY_GREENTICK_X = 990,
	PAY_GREENTICK_Y = 600,
	PAY_BIDV_X = 450,
	PAY_BIDV_Y = 500,
	PAY_MOMO_X = 650,
	PAY_MOMO_Y = 500,
	PAY_TPBANK_X = 850,
	PAY_TPBANK_Y = 500,
	PAY_VIETTELPAY_X = 1050,
	PAY_VIETTELPAY_Y = 500,
	PAY_OK_X = 260,
	PAY_OK_Y = 550,
	PAY_SALE_X = 500,
	PAY_SALE_Y = 150,
	PAY_ENTER_NAME_X = 450,
	PAY_ENTER_NAME_Y = 250,
	PAY_BOX_NAME_X = 450,
	PAY_BOX_NAME_Y = 280,
	PAY_NAME_WORD_X = 490,
	PAY_NAME_WORD_Y = 285,
	PAY_ENTER_VALUE_X = 450,
	PAY_ENTER_VALUE_Y = 350,
	PAY_BOX_VALUE_X = 450,
	PAY_BOX_VALUE_Y = 380,
	PAY_VALUE_WORD_X = 490,
	PAY_VALUE_WORD_Y = 385,
	PAY_BOX_RESULT_X = 200,
	PAY_BOX_RESULT_Y = 300,
	PAY_RESULT_WORD_X = 250,
	PAY_RESULT_WORD_Y = 375,
	PAY_CHOOSE_BANK_X = 450,
	PAY_CHOOSE_BANK_Y = 450
};

enum HelpFeature
{
	HELP_RULE1,
	HELP_RULE2,
	HELP_HOWTOPLAY,
	HELP_SKILL_CHAR1,
	HELP_SKILL_CHAR2,
	HELP_SKILL_CHAR3,
	HELP_SKILL_CHAR4,
	HELP_DOT1,
	HELP_DOT2,
	HELP_DOT3,
	HELP_DOT4,
	HELP_DOT5,
	HELP_DOT6,
	HELP_DOT7,
	ALLHELP
};

enum HelpSize
{
	HELP_RULE1_WIDTH = 1000,
	HELP_RULE1_HEIGHT = 700,
	HELP_RULE2_WIDTH = 1000,
	HELP_RULE2_HEIGHT = 700,
	HELP_HOWTOPLAY_WIDTH = 1000,
	HELP_HOWTOPLAY_HEIGHT = 700,
	HELP_SKILL_CHAR1_WIDTH = 1000,
	HELP_SKILL_CHAR1_HEIGHT = 700,
	HELP_SKILL_CHAR2_WIDTH = 1000,
	HELP_SKILL_CHAR2_HEIGHT = 700,
	HELP_SKILL_CHAR3_WIDTH = 1000,
	HELP_SKILL_CHAR3_HEIGHT = 700,
	HELP_SKILL_CHAR4_WIDTH = 1000,
	HELP_SKILL_CHAR4_HEIGHT = 700,
	HELP_DOT1_WIDTH = 10,
	HELP_DOT1_HEIGHT = 10,
	HELP_DOT2_WIDTH = 10,
	HELP_DOT2_HEIGHT = 10,
	HELP_DOT3_WIDTH = 10,
	HELP_DOT3_HEIGHT = 10,
	HELP_DOT4_WIDTH = 10,
	HELP_DOT4_HEIGHT = 10,
	HELP_DOT5_WIDTH = 10,
	HELP_DOT5_HEIGHT = 10,
	HELP_DOT6_WIDTH = 10,
	HELP_DOT6_HEIGHT = 10,
	HELP_DOT7_WIDTH = 10,
	HELP_DOT7_HEIGHT = 10,

};

enum HelpPosition
{
	HELP_RULE1_X = 200,
	HELP_RULE1_Y = 50,
	HELP_RULE2_X = 200,
	HELP_RULE2_Y = 50,
	HELP_HOWTOPLAY_X = 200,
	HELP_HOWTOPLAY_Y = 50,
	HELP_SKILL_CHAR1_X = 200,
	HELP_SKILL_CHAR1_Y = 50,
	HELP_SKILL_CHAR2_X = 200,
	HELP_SKILL_CHAR2_Y = 50,
	HELP_SKILL_CHAR3_X = 200,
	HELP_SKILL_CHAR3_Y = 50,
	HELP_SKILL_CHAR4_X = 200,
	HELP_SKILL_CHAR4_Y = 50,
	HELP_DOT1_X = 400,
	HELP_DOT1_Y = 770,
	HELP_DOT2_X = 500,
	HELP_DOT2_Y = 770,
	HELP_DOT3_X = 600,
	HELP_DOT3_Y = 770,
	HELP_DOT4_X = 700,
	HELP_DOT4_Y = 770,
	HELP_DOT5_X = 800,
	HELP_DOT5_Y = 770,
	HELP_DOT6_X = 900,
	HELP_DOT6_Y = 770,
	HELP_DOT7_X = 1000,
	HELP_DOT7_Y = 770
};

enum PlayingScreen
{
	PLAYING_AVATAR1,
	PLAYING_AVATAR2,
	PLAYING_AVATAR3,
	PLAYING_AVATAR4,
	PLAYING_TOTAL_HP1,
	PLAYING_TOTAL_HP2,
	PLAYING_TOTAL_HP3,
	PLAYING_TOTAL_HP4,
	PLAYING_CURRENT_HP1,
	PLAYING_CURRENT_HP2,
	PLAYING_CURRENT_HP3,
	PLAYING_CURRENT_HP4,
	PLAYING_SCORE,
	PLAYING_TIME,
	ALLPLAYING
};

enum PlayingSize
{
	PLAYING_AVATAR1_WIDTH = 15,
	PLAYING_AVATAR1_HEIGHT = 10,
	PLAYING_AVATAR2_WIDTH = 15,
	PLAYING_AVATAR2_HEIGHT = 10,
	PLAYING_AVATAR3_WIDTH = 15,
	PLAYING_AVATAR3_HEIGHT = 10,
	PLAYING_AVATAR4_WIDTH = 15,
	PLAYING_AVATAR4_HEIGHT = 10,
	PLAYING_TOTAL_HP1_WIDTH = 70,
	PLAYING_TOTAL_HP1_HEIGHT = 10,
	PLAYING_TOTAL_HP2_WIDTH = 70,
	PLAYING_TOTAL_HP2_HEIGHT = 10,
	PLAYING_TOTAL_HP3_WIDTH = 70,
	PLAYING_TOTAL_HP3_HEIGHT = 10,
	PLAYING_TOTAL_HP4_WIDTH = 70,
	PLAYING_TOTAL_HP4_HEIGHT = 10,
	PLAYING_CURRENT_HP1_WIDTH = 70,
	PLAYING_CURRENT_HP1_HEIGHT = 10,
	PLAYING_CURRENT_HP2_WIDTH = 70,
	PLAYING_CURRENT_HP2_HEIGHT = 10,
	PLAYING_CURRENT_HP3_WIDTH = 70,
	PLAYING_CURRENT_HP3_HEIGHT = 10,
	PLAYING_CURRENT_HP4_WIDTH = 70,
	PLAYING_CURRENT_HP4_HEIGHT = 10,
	PLAYING_SCORE_WIDTH = 150,
	PLAYING_SCORE_HEIGHT = 20,
	PLAYING_TIME_WIDTH = 150,
	PLAYING_TIME_HEIGHT = 20,
};

enum PlayingPosition
{
	PLAYING_AVATAR1_X = 2,
	PLAYING_AVATAR1_Y = 2,
	PLAYING_AVATAR2_X = 2,
	PLAYING_AVATAR2_Y = 14,
	PLAYING_AVATAR3_X = 2,
	PLAYING_AVATAR3_Y = 26,
	PLAYING_AVATAR4_X = 2,
	PLAYING_AVATAR4_Y = 38,
	PLAYING_TOTAL_HP1_X = 19,
	PLAYING_TOTAL_HP1_Y = 2,
	PLAYING_TOTAL_HP2_X = 19,
	PLAYING_TOTAL_HP2_Y = 14,
	PLAYING_TOTAL_HP3_X = 19,
	PLAYING_TOTAL_HP3_Y = 26,
	PLAYING_TOTAL_HP4_X = 19,
	PLAYING_TOTAL_HP4_Y = 38,
	PLAYING_CURRENT_HP1_X = 19,
	PLAYING_CURRENT_HP1_Y = 2,
	PLAYING_CURRENT_HP2_X = 19,
	PLAYING_CURRENT_HP2_Y = 14,
	PLAYING_CURRENT_HP3_X = 19,
	PLAYING_CURRENT_HP3_Y = 26,
	PLAYING_CURRENT_HP4_X = 19,
	PLAYING_CURRENT_HP4_Y = 38,
	PLAYING_SCORE_X = 625,
	PLAYING_SCORE_Y = 5,
	PLAYING_TIME_X = 625,
	PLAYING_TIME_Y = 5,
};

enum PlayingSummary
{
	SUMMARY_WINDOW,
	SUMMARY_WIN_LOSE,
	SUMMARY_SCORE_TIME,
	SUMMARY_CHAR1,
	SUMMARY_CHAR2,
	SUMMARY_CHAR3,
	SUMMARY_CHAR4,
	SUMMARY_HPLEFT,
	SUMMARY_HPLEFT1,
	SUMMARY_HPLEFT2,
	SUMMARY_HPLEFT3,
	SUMMARY_HPLEFT4,
	SUMMARY_TOTALHP1,
	SUMMARY_TOTALHP2,
	SUMMARY_TOTALHP3,
	SUMMARY_TOTALHP4,
	SUMMARY_REPLAY,
	SUMMARY_HOME,
	SUMMARY_NEXT,
	ALLSUMMARY
};

enum PlayingSummarySize
{
	SUMMARY_WINDOW_WIDTH = 1200,
	SUMMARY_WINDOW_HEIGHT = 700,
	SUMMARY_WIN_LOSE_WIDTH = 200,
	SUMMARY_WIN_LOSE_HEIGHT = 90,
	SUMMARY_SCORE_TIME_WIDTH = 400,
	SUMMARY_SCORE_TIME_HEIGHT = 70,
	SUMMARY_CHAR1_WIDTH = 50,
	SUMMARY_CHAR1_HEIGHT = 50,
	SUMMARY_CHAR2_WIDTH = 50,
	SUMMARY_CHAR2_HEIGHT = 50,
	SUMMARY_CHAR3_WIDTH = 50,
	SUMMARY_CHAR3_HEIGHT = 50,
	SUMMARY_CHAR4_WIDTH = 50,
	SUMMARY_CHAR4_HEIGHT = 50,
	SUMMARY_HPLEFT_WIDTH = 150,
	SUMMARY_HPLEFT_HEIGHT = 40,
	SUMMARY_HPLEFT1_WIDTH = 300,
	SUMMARY_HPLEFT1_HEIGHT = 50,
	SUMMARY_HPLEFT2_WIDTH = 300,
	SUMMARY_HPLEFT2_HEIGHT = 50,
	SUMMARY_HPLEFT3_WIDTH = 300,
	SUMMARY_HPLEFT3_HEIGHT = 50,
	SUMMARY_HPLEFT4_WIDTH = 300,
	SUMMARY_HPLEFT4_HEIGHT = 50,
	SUMMARY_TOTALHP1_WIDTH = 300,
	SUMMARY_TOTALHP1_HEIGHT = 50,
	SUMMARY_TOTALHP2_WIDTH = 300,
	SUMMARY_TOTALHP2_HEIGHT = 50,
	SUMMARY_TOTALHP3_WIDTH = 300,
	SUMMARY_TOTALHP3_HEIGHT = 50,
	SUMMARY_TOTALHP4_WIDTH = 300,
	SUMMARY_TOTALHP4_HEIGHT = 50,
	SUMMARY_REPLAY_WIDTH = 100,
	SUMMARY_REPLAY_HEIGHT = 100,
	SUMMARY_HOME_WIDTH = 100,
	SUMMARY_HOME_HEIGHT = 100,
	SUMMARY_NEXT_WIDTH = 100,
	SUMMARY_NEXT_HEIGHT = 100
};

enum PlayingSummaryPosition
{
	SUMMARY_WINDOW_X = 100,
	SUMMARY_WINDOW_Y = 50,
	SUMMARY_WIN_LOSE_X = 600,
	SUMMARY_WIN_LOSE_Y = 70,
	SUMMARY_SCORE_TIME_X = 770,
	SUMMARY_SCORE_TIME_Y = 310,
	SUMMARY_CHAR1_X = 300,
	SUMMARY_CHAR1_Y = 340,
	SUMMARY_CHAR2_X = 300,
	SUMMARY_CHAR2_Y = 410,
	SUMMARY_CHAR3_X = 300,
	SUMMARY_CHAR3_Y = 480,
	SUMMARY_CHAR4_X = 300,
	SUMMARY_CHAR4_Y = 550,
	SUMMARY_HPLEFT_X = 400,
	SUMMARY_HPLEFT_Y = 280,
	SUMMARY_HPLEFT1_X = 360,
	SUMMARY_HPLEFT1_Y = 340,
	SUMMARY_HPLEFT2_X = 360,
	SUMMARY_HPLEFT2_Y = 410,
	SUMMARY_HPLEFT3_X = 360,
	SUMMARY_HPLEFT3_Y = 480,
	SUMMARY_HPLEFT4_X = 360,
	SUMMARY_HPLEFT4_Y = 550,
	SUMMARY_TOTALHP1_X = 360,
	SUMMARY_TOTALHP1_Y = 340,
	SUMMARY_TOTALHP2_X = 360,
	SUMMARY_TOTALHP2_Y = 410,
	SUMMARY_TOTALHP3_X = 360,
	SUMMARY_TOTALHP3_Y = 480,
	SUMMARY_TOTALHP4_X = 360,
	SUMMARY_TOTALHP4_Y = 550,
	SUMMARY_REPLAY_X = 780,
	SUMMARY_REPLAY_Y = 470,
	SUMMARY_HOME_X = 930,
	SUMMARY_HOME_Y = 470,
	SUMMARY_NEXT_X = 1080,
	SUMMARY_NEXT_Y = 470
};

#endif enum_h_